### ISSUE TITLE
feature links don't render anything

### ISSUE THREAD

**Issue by ITwrx** [arctic-hen7/arctic-hen7.github.io#10]
hi,
just making sure you're aware that the feature blocks for [Perseus](https://arctic-hen7.github.io/perseus/en-US/) don't render anything and all have the same url slug [/static-generation](https://arctic-hen7.github.io/perseus/en-US/docs/feature/static-generation).
Thanks

**Comment by arctic-hen7** [comment]
Yes, I am! Sorry, I'm rebuilding the docs at the moment, and those feature blocks been left behind a little. I'm redesigning that landing page today, actually, so that will all hopefully be fixed quite soon!

(Btw, issues about the Perseus website should be filed on the Perseus repo in future.)
